[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18.20.0"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/r/*"
  to = "/index.html"
  status = 200
